### PR TITLE
Allow custom manifest in war/ subdirectory

### PR DESCRIPTION
**Pull request by samspycher**
A custom manifest in war/META-INF/MANIFEST.MF caused the build to fail, because it was colliding with the automatically generated manifest file. Now a MANIFEST.MF is only automatically generated if no custom file exists.

### CODE REVIEW

**Comment by samspycher** [comment]
A note to the code: I don't have much experience at all on Scala, and couldn't figure out how to do the case distinction with the option variable more elegantly... perhaps you can improve this? 

Also, I made the search for MANIFEST.MF case-insensitive, since the spec for jar seems to reserve other cases also (see http://docs.oracle.com/javase/6/docs/technotes/guides/jar/jar.html, search for 'case-insensitive'), and I am unsure if certain containers would possibly also accept different casing.

**Comment by dlecan** [comment]
I will add later some debug informations.

**Comment by dlecan** [comment]
Play2War v0.7.1 is out, including a fix for this issue.

**Comment by mdebusschere** [comment]
Is this valid for play 2.2.0 and play2-war-plugin 1.2-beta2 ?

Building on Windows 7 with Java 7.

Build fails due to conflict
[trace] Stack trace suppressed: run last *:war for the full output.
[error](*:war) java.util.zip.ZipException: duplicate entry: META-INF/MANIFEST.MF

Using custom web.xml files appears to work.  Also, when I use a lowercase 
filename  manifest.mf, the WAR and ends up with TWO manifest.mf files.

**Comment by dlecan** [comment]
@mdebusschere Please report a separate issue, thank you.

**Pull request merged**
