### PR TITLE
Change Play2Servlet for Container 2.5 and 3.0 to make it works on glassfish

### PR DESCRIPTION
**Pull request by dsapandora**
Modify  Play2Servlet to make a correctly deploy on glassfish. Glassfish doesn't like the way that GenericPlay2Servlet was implemented  to generate the jar files needed to create the WAR . For that reasons WAR got the 404 error when is deployed.  After a lot of research I change the way that Play2Servlet is implemented. With this fix, the WAR generated can be deployed correctly

### CODE REVIEW

**Comment by dlecan** [comment]
Which version of Glassfish ?

Interesting, but a lot of duplicated code :)
What about putting duplicated code in a trait ?

### Original hierarchy:

```
                       HttpServlet (abstract)
                             ^
                             |
                GenericPlay2Servlet (abstract)
                 ^                     ^
                /                       \
           Play2Servlet25          Play2Servlet30
```

### Your proposal:

```
                  HttpServlet (abstract)
                 ^                     ^
                /                       \
           Play2Servlet25          Play2Servlet30
```

### A new poposal:

```
Play2Servlet (trait)         HttpServlet (abstract)     Play2Servlet (trait)
               ^               ^                ^              ^
                \             /                  \            /
                 Play2Servlet25                  Play2Servlet30
```

The two `Play2Servlet (trait)` are the same for course :)

Does it work with Glassfish ?

**Comment by dsapandora** [comment]
I was using Glassfish 3.1.2, but the issue is about his weird form to deploy apps. I will take your advise and Try this evening... thanks for the comments

**Comment by dlecan** [comment]
Any news ?

**Comment by dlecan** [comment]
Your idea is good. Any news ?

**Pull request closed without merging**
