### PR TITLE
fix issue #280: compatibility with play 2.3.8

### PR DESCRIPTION
**Pull request by yanns**
The compatibility with other versions from play 2.3.x is
maintained as shown be the tests.

### CODE REVIEW

**Comment by yanns** [comment]
@dlecan in my opinion, this branch can be merged.
After that, we need to publish a new version.

**Comment by yanns** [comment]
@dlecan Thanks for the version.
Maybe you should change the description of this release.
It _is_ compatible with play 2.3.x, even lower versions as 2.3.8

**Comment by yanns** [comment]
@dlecan I changed the description after having check is again. 
The integration tests are run with a play 2.3.2 application.

**Comment by dlecan** [comment]
@yanns thank you for checking that :)

**Pull request merged**
