### PR TITLE
sbt project is loading without errors + migration from Build.scala to build.sbt

### PR DESCRIPTION
**Pull request by pwyczes**
When I forked the repo, sbt project was not loading on branch develop.
I figured it out, that there was an old sbt version in use, and "com.typesafe" % "config" was missing from both plugins and source code, so I added it.
I might start working on https://github.com/play2war/play2-war-plugin/issues/321 after this fix.

### CODE REVIEW

**Comment by pwyczes** [comment]
Hi there, is there anything else I can do in order to push this pull request forward? :)

**Comment by yanns** [comment]
Hi @pwyczes 
Thx for the PR.
I'm back from vacations and will take some time to look at your PR(s) after I'm back into daily business.
Please have some patience, thx!

**Comment by pwyczes** [comment]
Hi @yanns 
I am just wondering if you had a chance to look at those PR(s)? :)
I am not rushing though. ;)

**Review by yanns — COMMENTED** [review]
Thx for the PR.

Could you please update the sbt version to the last one `0.13.17`. The `0.13.16` fixes loading sbt on certain terminals.

Otherwise good work 👍

**Comment by pwyczes** [comment]
Thank you. :)
I've changed it to `0.13.17` in the github editor, which created new commits - is it ok?

**Review by yanns — APPROVED** [review]
🥇

**Pull request merged**
